defaults:
  - cameras: real
  - _self_

type: pi
action_type: jointvel

model_name: ???
model_dir: null
checkpoints: null
use_torch: false
buffer_length: -1
compile_mode: max-autotune-no-cudagraphs
max_joint_delta: 0.2
