robot:
  robot_host: ???

  gripper:
    speed: 0.085
    force: 10.0

  cameras:
    wrist_camera:
      type: "zed"
      id: 15679333
      width: 1280
      height: 720
      frame_rate: 30
      side: "left"
      depth: false
    exo_camera_1:
      type: "zed"
      id: 26706125
      width: 1280
      height: 720
      frame_rate: 30
      side: "left"
      depth: false

policy_host: "0.0.0.0"
policy_port: 8000
policy_dt: 0.066
action_scale: 1.0
task: "???"

image_input:
  width: 640
  height: 360
  method: "downsample"

wandb:
  enabled: false
  entity: null
  project: null
  name: "franka_eval"
  tags: null
  notes: null

autohome:
  enabled: true
  duration: 5.0
  home_jointpos: [0.0, -0.7, 0.0, -2.35619, 0.0, 1.57079, 0.0]
